spring:
    application:
        name: springboot-admin
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 12345
        url: jdbc:mysql://localhost:3306/icatw?serverTimezone=GMT%2b8
        username: root
server:
    port: 9090
